/**
 * Generates src/app/core/icons.generated.ts — the only icon glyphs the site ships.
 *
 *   SYMBOLS  Material Symbols Rounded (weight 500), viewBox "0 -960 960 960"
 *   BRANDS   Simple Icons brand marks, viewBox "0 0 24 24"
 *
 * Inlining just the paths we use keeps the bundle tiny (the full rounded icon
 * font is ~5 MB) and avoids loading fonts from Google (GDPR).
 *
 * Add a name to the lists below, then run:  npm run icons
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import * as si from 'simple-icons';

const require = createRequire(import.meta.url);

const SYMBOL_NAMES = [
  // chrome
  'dark_mode', 'light_mode', 'close', 'arrow_forward', 'arrow_right', 'keyboard_arrow_down',
  'location_on', 'verified', 'translate', 'search', 'inbox', 'code', 'shield', 'gavel',
  // skills view + sort
  'dashboard', 'grid_view', 'shuffle', 'trending_down', 'sort_by_alpha', 'category',
  // skill categories
  'web', 'dns', 'cloud', 'database', 'construction', 'palette',
  // skills without a brand mark
  'tag', 'swap_horiz', 'cloud_circle', 'all_inclusive', 'storage', 'integration_instructions',
  'code_blocks', 'table_view', 'api', 'hub', 'layers', 'apps', 'bolt', 'assignment', 'schema',
  'design_services', 'sprint', 'widgets', 'manage_search', 'smart_toy', 'move_to_inbox', 'hexagon',
  // projects
  'psychology', 'pets', 'coffee_maker', 'skillet', 'checklist', 'directions_car', 'view_in_ar', 'rocket_launch'
];

const BRAND_KEYS = {
  angular: 'siAngular', typescript: 'siTypescript', javascript: 'siJavascript', dart: 'siDart',
  cplusplus: 'siCplusplus', primeng: 'siPrimeng', tailwindcss: 'siTailwindcss', blazor: 'siBlazor',
  progress: 'siProgress', flutter: 'siFlutter', bootstrap: 'siBootstrap', react: 'siReact',
  html5: 'siHtml5', css: 'siCss', dotnet: 'siDotnet', apachekafka: 'siApachekafka', docker: 'siDocker',
  kubernetes: 'siKubernetes', helm: 'siHelm', terraform: 'siTerraform', gitlab: 'siGitlab',
  githubactions: 'siGithubactions', git: 'siGit', sonar: 'siSonar', grafana: 'siGrafana',
  keycloak: 'siKeycloak', firebase: 'siFirebase', mysql: 'siMysql', mongodb: 'siMongodb',
  appwrite: 'siAppwrite', rider: 'siRider', postman: 'siPostman', figma: 'siFigma', jira: 'siJira',
  confluence: 'siConfluence', miro: 'siMiro', claude: 'siClaude', mermaid: 'siMermaid',
  xcode: 'siXcode', reactivex: 'siReactivex', materialdesign: 'siMaterialdesign', adyen: 'siAdyen',
  devexpress: 'siDevexpress', modelcontextprotocol: 'siModelcontextprotocol'
};

const dir = require.resolve('@material-symbols/svg-500/package.json').replace(/package\.json$/, 'rounded/');
const symbols = {};
for (const name of SYMBOL_NAMES) {
  const svg = readFileSync(`${dir}${name}.svg`, 'utf8');
  const d = svg.match(/ d="([^"]+)"/)?.[1];
  if (!d) throw new Error(`No path in ${name}.svg`);
  symbols[name] = d;
}

const brands = {};
for (const [key, exportName] of Object.entries(BRAND_KEYS)) {
  const icon = si[exportName];
  if (!icon) throw new Error(`simple-icons has no ${exportName}`);
  brands[key] = { title: icon.title, path: icon.path };
}

const out = `/* eslint-disable */
// GENERATED by scripts/gen-icons.mjs — do not edit by hand. Run \`npm run icons\`.
// Material Symbols (Apache-2.0) · Simple Icons (CC0-1.0; brand marks belong to their owners).

/** Material Symbols Rounded path data, viewBox "0 -960 960 960". */
export const SYMBOLS: Readonly<Record<string, string>> = ${JSON.stringify(symbols, null, 2)};

/** Simple Icons brand marks, viewBox "0 0 24 24". */
export const BRANDS: Readonly<Record<string, { title: string; path: string }>> = ${JSON.stringify(brands, null, 2)};
`;
writeFileSync(new URL('../src/app/core/icons.generated.ts', import.meta.url), out);
console.log(`icons.generated.ts — ${SYMBOL_NAMES.length} symbols, ${Object.keys(brands).length} brands`);
